@startuml
'https://plantuml.com/sequence-diagram

autonumber

Administrador -> ConnectorApi: /api/
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml