/**
 * MAAS API
 * This is the Mobility as a Service API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: avalls@nexusgeographics.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CreditCard } from './creditCard';


/**
 * Account data.
 */
export interface Account {
    accountID: number;
    companyName?: string;
    type: Account.TypeEnum;
    creditCard?: CreditCard;
}
export namespace Account {
    export type TypeEnum = 'unipersonal' | 'fleet';
    export const TypeEnum = {
        Unipersonal: 'unipersonal' as TypeEnum,
        Fleet: 'fleet' as TypeEnum
    }
}
