/**
 * MAAS API
 * This is the Mobility as a Service API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: avalls@nexusgeographics.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Defines the configuration and behaviour of the apps.
 */
export interface AppConfig {
    /**
     * Indicates if automated stop detection using predict.io is enable.
     */
    isPredictioOn: boolean;
    prevision: boolean;
    previsionBlue: boolean;
    previsionGreen: boolean;
    previsionOffstreet: boolean;
    /**
     * Comes from global configuration
     */
    termsVersion: string;
    /**
     * Comes from global configuration
     */
    termsLink: string;
    /**
     * Comes from global configuration
     */
    minAndroidVersion: string;
    /**
     * Comes from global configuration
     */
    minIosVersion: string;
}
