/**
 * MAAS API
 * This is the Mobility as a Service API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: avalls@nexusgeographics.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AvailabilitySectionPoints } from './availabilitySectionPoints';


export interface AvailabilitySection {
    sectionID: number;
    /**
     * ?????
     */
    a: boolean;
    color: string;
    description: string;
    /**
     * The two points
     */
    points: Array<AvailabilitySectionPoints>;
    /**
     * Section type: verda, blava, parquing
     */
    type: number;
}
