/**
 * MAAS API
 * This is the Mobility as a Service API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: avalls@nexusgeographics.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ByTopicRequest {
    notificationId: number;
    /**
     * The topics to which send. If more than one, OR is used. For example if topics are IOS and ANDROID it will send to all users.
     */
    topics: Array<string>;
}
