/**
 * Smou API
 * This is the Mobility as a Service API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: avalls@nexusgeographics.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { VacationDay } from './vacationDay';
import { ScheduleCityConf } from './scheduleCityConf';
import { RateCityConf } from './rateCityConf';
import { ZoneType } from './zoneType';


export interface ConfigurationConf {
    configurationId: number;
    name: string;
    /**
     * Autogenerated. Join with rate and schedule description
     */
    description?: string;
    startDate: Date;
    endDate: Date;
    zoneTypeId: number;
    rateId: number;
    scheduleId: number;
    vacations?: Array<VacationDay>;
    deletedDate?: string;
    schedule?: ScheduleCityConf;
    rate?: RateCityConf;
    zone?: ZoneType
}
