/**
 * Dum API
 * This is the DUM API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: rbarbado@nexusgeographics.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { JuridicEntity } from './juridicEntity';
import { Rate } from './rate';
import { Schedule } from './schedule';
import { VacationDay } from './vacationDay';
import { ZoneTypeAll } from './zoneTypeAll';


export interface ConfigurationAll { 
    /**
     * Configuration ID
     */
    configurationId: number;
    rateDb?: Rate;
    scheduleDb?: Schedule;
    zoneTypeDb?: ZoneTypeAll;
    juridicEntityDb?: JuridicEntity;
    /**
     * Name
     */
    configurationName?: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Start date
     */
    startDate?: Date;
    /**
     * End date
     */
    endDate?: Date;
    /**
     * Vacation information
     */
    vacations?: Array<VacationDay>;
}
