/**
 * MAAS API
 * This is the Mobility as a Service API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: avalls@nexusgeographics.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Generic object used as a standard error response.  Login error codes: * #10001: example  Parking error codes: * #20001: If the price > 0 and no credit card is configured. * #20002: Chained parkings detected.  
 */
export interface ErrorGeneric {
    /**
     * Status of the response, usually 400
     */
    status: number;
    /**
     * Code of the response, used to handle multilingual
     */
    code: number;
    /**
     * Description of the error in english
     */
    message: string;
}
