/**
 * MAAS API
 * This is the Mobility as a Service API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: avalls@nexusgeographics.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Gremi {
    gemiId: number;
    nameGremi: string;
    name: string;
    dateConv: Date;
    email: string;
    dni: string;
    phone: string;
    direction: string;
    city: string;
    zip: string;
    nameCompany: string;
    codGremi: string;
    description: string;
    permissionsDUM: boolean;
    permissionsBSM: boolean;
}

