/**
 * Spro - Area Dum
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GuildCard } from './guildCard';

/**
 * 
 */
export interface GuildCardOperation { 
    /**
     * Operation id
     */
    op_id: number;
    /**
     * 
     */
   	op_guildCardId: number;
    op_guildCardNumber: number;
    op_type : string;
	
	op_guildCardGuildId: number;
	op_guildCardCurrentBalance: number;
	op_guildCardInitialBalance: number;
    /**
     * data de la operació
     */
    op_date: number;
    /**
     * descripció de la operació
     */
    op_discountPercent: number;
	op_parkingCode: string;
	op_discountAmount: number;
	op_discountTimeUsed: number;
	op_guildTOW: string;
}
