/**
 * Smou API
 * This is the Mobility as a Service API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: avalls@nexusgeographics.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { I18n } from './i18n';
import { ModifierOrigin } from './modifierOrigin';
import { ModifierType } from './modifierType';


export interface ModifierConf { 
    modifierId: number;
    modifierValue: number;
    modifierType: ModifierType;
    modifierOrigin: ModifierOrigin;
    configurations?: Array<number>
    deletedDate?: string;
    description: I18n;
}
