/**
 * MAAS API
 * This is the Mobility as a Service API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: avalls@nexusgeographics.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NotificationType } from './notificationType';


export interface NotificationData {
    titleCa: string;
    titleEs: string;
    titleEn: string;
    messageCa: string;
    messageEs: string;
    messageEn: string;
    notificationType: NotificationType;
    forAll: boolean;
    urlCa?: string;
    urlEs?: string;
    urlEn?: string;
}
