/**
 * MAAS API
 * This is the Mobility as a Service API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: avalls@nexusgeographics.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface OAuthDetails {
    access_token: string;
    token_type: string;
    refresh_token: string;
    expires_in: number;
    scope: string;
    psetCreditCard?: boolean;
    paddVehicles?: boolean;
    plegalEntityList?: string;
    pisAdmin?: boolean;
    pfineAnnulation?: boolean;
    jti: string;
    userId: number;
    _body: any;
}
