/**
 * MAAS API
 * This is the Mobility as a Service API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: avalls@nexusgeographics.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Permissions {
    isAdmin: boolean;
    setCreditCard: boolean;
    addVehicles: boolean;
    legalEntityList?: string;
    userId?: number;
    fineAnnulation: boolean;
}
