/**
 * Smou API
 * This is the Mobility as a Service API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: avalls@nexusgeographics.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { I18n } from './i18n';


export interface RateCityConf {
    rateId: number;
    rateCode: string;
    description: string;
    description_i18n: I18n;
    maxParkingTime: number;
    xMinute: Array<number>;
    /**
     * Data de la eliminació
     */
    deletedDate?: string;
    inUse?: boolean;
}
