/**
 * Smou API
 * This is the Mobility as a Service API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: avalls@nexusgeographics.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ServiceStatus { 
    /**
     * Indicates if the given user has this service activated.
     */
    active: boolean;
    /**
     * If the user has an active ticket, returns the ticketId. Null if there is no active ticket.
     */
    activeTicketId?: number;
    /**
     * Id of the given service
     */
    serviceId: number;
}
