/**
 * Smou API
 * This is the Mobility as a Service API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: avalls@nexusgeographics.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PaymentGateway } from './paymentGateway';
import { Statistic } from './statistic';


export interface Statistics { 
    operationsPerDay: Statistic;
    operationsPerHour: Statistic;
    incidents: Statistic;
    accionsAtClient: Statistic;
    operationsCourseSMS: number;
    operationsCourse: Statistic;
    operativeSSCC: PaymentGateway;
}
