/**
 * MAAS API
 * This is the Mobility as a Service API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: avalls@nexusgeographics.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TermsRequest {
    /**
     * Array because  there are always 3 active for the 3 checks in the app. Add into the array the ones that you want to accept
     */
    privacyPolicies: Array<number>;
    /**
     * Service conditions to accept.
     */
    serviceConditions: number;
}
