/**
 * MAAS API
 * This is the Mobility as a Service API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: avalls@nexusgeographics.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { AuditLog } from '../model/auditLog';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class AuditService {

    protected basePath = 'http://maas.nexusgeografics.com/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Get audit logs depending of the paremeters
     * 
     * @param authorization 
     * @param actionType 
     * @param userOwner 
     * @param actionDate 
     * @param actionDateRange 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public auditsGet(authorization: string, actionType?: string, userOwner?: string, actionDate?: string, actionDateRange?: Array<string>, observe?: 'body', reportProgress?: boolean): Observable<AuditLog>;
    public auditsGet(authorization: string, actionType?: string, userOwner?: string, actionDate?: string, actionDateRange?: Array<string>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AuditLog>>;
    public auditsGet(authorization: string, actionType?: string, userOwner?: string, actionDate?: string, actionDateRange?: Array<string>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AuditLog>>;
    public auditsGet(authorization: string, actionType?: string, userOwner?: string, actionDate?: string, actionDateRange?: Array<string>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling auditsGet.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (actionType !== undefined) {
            queryParameters = queryParameters.set('actionType', <any>actionType);
        }
        if (userOwner !== undefined) {
            queryParameters = queryParameters.set('userOwner', <any>userOwner);
        }
        if (actionDate !== undefined) {
            queryParameters = queryParameters.set('actionDate', <any>actionDate);
        }
        if (actionDateRange) {
            actionDateRange.forEach((element) => {
                queryParameters = queryParameters.append('actionDateRange', <any>element);
            })
        }

        let headers = this.defaultHeaders;
        if (authorization !== undefined && authorization !== null) {
            headers = headers.set('Authorization', String(authorization));
        }

        // authentication (MaaS Token) required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<AuditLog>(`${this.basePath}/audits`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
