# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/

##########################################################
#######################DEPRECATED#########################
##########################################################
# Només s'utilitza per generar versions antigues.

.node: &node
  image: node:10
  before_script:
    - npm install
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
    - node_modules/

variables:
  DOCKER_FARM: 192.168.0.55

stages:
  - deploy

deploy_develop:
  stage: deploy
  tags:
    #- nodejs
    - nodejs12
  environment:
    name: dev
  <<: *node
  script:
    - sshpass -p "$DOCKERFARM_PASS" ssh $DOCKERFARM_USER@$DOCKER_FARM 'cd /usr/nexus/docker/dum/dum-nginx-bo && rm -f dist-pre.tar && rm -rf www/*'
    - npm run build -- --base-href=/bo/ --deploy-url=/bo/ -c=$CI_ENVIRONMENT_SLUG
    - sshpass -p "$DOCKERFARM_PASS" rsync -avrc --delete  dist/ $DOCKERFARM_USER@$DOCKER_FARM:/usr/nexus/docker/dum/dum-nginx-bo/www
  only:
    - dev_nexus
    
deploy_develop_zonabus:
  stage: deploy
  tags:
    - nodejs
  environment:
    name: dev
  <<: *node
  script:
    - sshpass -p "$DOCKERFARM_PASS" ssh $DOCKERFARM_USER@$DOCKER_FARM 'cd /usr/nexus/docker/dum/dum-nginx-bo && rm -f dist-pre.tar && rm -rf www/*'
    - npm run build -- --base-href=/bo/ --deploy-url=/bo/ -c=$CI_ENVIRONMENT_SLUG
    - sshpass -p "$DOCKERFARM_PASS" rsync -avrc --delete  dist/ $DOCKERFARM_USER@$DOCKER_FARM:/usr/nexus/docker/dum/dum-nginx-bo/www
  only:
    - dev_zona_bus

deploy_production:
  stage: deploy
  tags:
    #- nodejs
    - nodejs12
  environment:
    name: pro
  <<: *node
  script:
    - npm run build -- --base-href=/bo/ --deploy-url=/bo/ -c=$CI_ENVIRONMENT_SLUG
    - cd dist
    - tar -cvf ../dist.tar *
    - sshpass -p "$DOCKERFARM_PASS" ssh $DOCKERFARM_USER@$DOCKER_FARM 'cd /usr/nexus/docker/dum/dum-nginx-bo && rm -f dist-pro.tar && rm -rf www/*'
    - sshpass -p "$DOCKERFARM_PASS" scp ../dist.tar $DOCKERFARM_USER@$DOCKER_FARM:/usr/nexus/docker/dum/dum-nginx-bo/dist-$CI_ENVIRONMENT_SLUG.tar
    - sshpass -p "$DOCKERFARM_PASS" ssh $DOCKERFARM_USER@$DOCKER_FARM 'cd /usr/nexus/docker/dum/dum-nginx-bo && tar -xvf dist-pro.tar --directory www && ./pro.sh '
  only:
    - master_old

deploy_pre:
  stage: deploy
  tags:
    #- nodejs
    - nodejs12
  environment:
    name: pre
  <<: *node
  script:
    - npm run build -- --base-href=/bo/ --deploy-url=/bo/ -c=$CI_ENVIRONMENT_SLUG
    - cd dist
    - tar -cvf ../dist.tar *
    - sshpass -p "$DOCKERFARM_PASS" ssh $DOCKERFARM_USER@$DOCKER_FARM 'cd /usr/nexus/docker/dum/dum-nginx-bo && rm -f dist-pre.tar;rm -rf www/*'
    - sshpass -p "$DOCKERFARM_PASS" scp ../dist.tar $DOCKERFARM_USER@$DOCKER_FARM:/usr/nexus/docker/dum/dum-nginx-bo/dist-$CI_ENVIRONMENT_SLUG.tar
    - sshpass -p "$DOCKERFARM_PASS" ssh $DOCKERFARM_USER@$DOCKER_FARM 'cd /usr/nexus/docker/dum/dum-nginx-bo && tar -xvf dist-pre.tar --directory www && ./dev.sh'
  only:
    - pre
